version: '3.3'

services:
  postgres:
    image: postgres:11.5-alpine
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  metabase:
    depends_on:
      - postgres
    image: metabase/metabase
    restart: always
    environment:
      JAVA_TIMEZONE: Europe/Paris
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: postgres
    ports:
      - '3000:3000'
    expose:
      - '3000'
